### ISSUE TITLE
TypeError: Cannot read property 'glob' of undefined

### ISSUE THREAD

**Issue by linbaicheng** [mikemartin/laravel-mix-pug-recursive#3]
### The background:

```
// webpack.mix.js

let mix = require('laravel-mix');
mix.pug = require('laravel-mix-pug-recursive');

mix.js('src/app.js', 'dist')
   .sass('src/app.scss', 'dist')
   .pug('src/**/*.pug', 'dist')
   .setPublicPath('dist');
```

Run `npx mix`

```
$ npx mix
```

Report errors below:

```
[webpack-cli] TypeError: Cannot read property 'glob' of undefined
    at Object.pug (/private/tmp/larvel/node_modules/laravel-mix-pug-recursive/src/index.js:17:30)
    at Object.<anonymous> (/private/tmp/larvel/webpack.mix.js:6:5)
    at Module._compile (/private/tmp/larvel/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/private/tmp/larvel/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/private/tmp/larvel/node_modules/laravel-mix/setup/webpack.config.js:8:5)
    at /private/tmp/larvel/node_modules/webpack-cli/lib/webpack-cli.js:1222:43
```

**Comment by hectorsevillasandoval** [comment]
Hey @linbaicheng, Could you try adding an empty object as a third parameter in here: 
`.pug('src/**/*.pug', 'dist',{})`

**Comment by mikemartin** [comment]
@linbaicheng Can confirm that @barcadictni's workaround will work. But this seems to be a regression from this bugfix from @RikutoYamaguchi 
https://github.com/mikemartin/laravel-mix-pug-recursive/commit/d474cdce836204b47e6c9e7c7fc9bffceb121080

**Comment by RikutoYamaguchi** [comment]
@mikemartin I'm sorry. Fixed a bug in https://github.com/mikemartin/laravel-mix-pug-recursive/pull/5

**Comment by mikemartin** [comment]
Thanks @RikutoYamaguchi for the fix. 👍

**Comment by linbaicheng** [comment]
> Hey @linbaicheng, Could you try adding an empty object as a third parameter in here:
> `.pug('src/**/*.pug', 'dist',{})`

@mikemartin @barcadictni  Thank you so much! 🙏

```diff
# webpack.mix.js
let mix = require('laravel-mix');
mix.pug = require('laravel-mix-pug-recursive');

mix.js('src/app.js', 'dist')
   .sass('src/app.scss', 'dist')
-   .pug('src/**/*.pug', 'dist')
+  .pug('src/**/*.pug', 'dist',{})
   .setPublicPath('dist');
```

### 👍 It's looking good. 

![image](https://user-images.githubusercontent.com/10935051/117828235-39db8300-b2a4-11eb-8769-115ce1bbedc5.png)

**Comment by hectorsevillasandoval** [comment]
> > Hey @linbaicheng, Could you try adding an empty object as a third parameter in here:
> > `.pug('src/**/*.pug', 'dist',{})`
> 
> @mikemartin @barcadictni Thank you so much! 🙏
> 
> ```diff
> # webpack.mix.js
> let mix = require('laravel-mix');
> mix.pug = require('laravel-mix-pug-recursive');
> 
> mix.js('src/app.js', 'dist')
>    .sass('src/app.scss', 'dist')
> -   .pug('src/**/*.pug', 'dist')
> +  .pug('src/**/*.pug', 'dist',{})
>    .setPublicPath('dist');
> ```
> 
> ### 👍 It's looking good.
> ![image](https://user-images.githubusercontent.com/10935051/117828235-39db8300-b2a4-11eb-8769-115ce1bbedc5.png)

Try adding this to the options:
`
.pug('src/**/*.pug', 'dist',{
excludePath: 'src'
})`
